### ISSUE TITLE
Is there a specific reason for the resource cache name choice?

### ISSUE THREAD

**Issue by joeyjurjens** [python-odin/odin#171]
I see that odin resources are immediately added to the cache by their meta class, and it does this by using the namespace and class name as key.

https://github.com/python-odin/odin/blob/801e34b60f4b907b4436d30488c9deacde5d9b16/src/odin/registration.py#L24C1-L37C54

I saw that the mapping cache key is more specific by using `.__module__`;
https://github.com/python-odin/odin/blob/801e34b60f4b907b4436d30488c9deacde5d9b16/src/odin/registration.py#L6-L7

Now, I was wondering if there's a specific reason that the `Resource` objects are less specific than the mapping one.
I'm asking because I was having odd behaviour due to conflicting names and not being able to create a resource.

If there's no specific reason, could I make a PR that uses __module__ like it does for the mapping?

**Comment by joeyjurjens** [comment]
I just saw that the ```class.__module__ `` `is actually used when not specifying a namespace yourself.

And I also figured out the issue that I had, inherited resources take the base resource namespace, which is why I have the side effects that I have.

**Comment by timsavage** [comment]
Hi Joey,

I'm sorry, but I'm just now able to respond. That is correct. The default behaviour is to use a namespace based on the package name. 

The types are cached and mapped so that codecs can resolve them from the type name stored in the serialised form. 

Namespaces became useful when documenting a schema for a specific use-case or for an API.

Cheers

**Comment by joeyjurjens** [comment]
No worries, in the end I figured it out :). Thanks for your answer anyways.

With `django-oscar`, almost every class, function etc us customizable by the end user with a utility function called `get_class`. I'm trying to make this work within `django-oscar-odin` as well, which you also worked on I think.

But I'm hitting the issue that it returns the base resource I was inheriting from.
So I might just document that the customized resources must have a custom name_space in order for it to work.

Thanks again!
