### ISSUE TITLE
Excluding fields using a ResourceAdapter with the exclude attribute doesn't work

### ISSUE THREAD

**Issue by thedrow** [python-odin/odin#37]
I have a resource adapter that excludes a field just like the documentation suggested:
```python
import odin
from odin.codecs import json_codec

class MyResource(odin.Resource):
  foo = odin.StringField()
  bar = odin.StringField()

class MyResourceAdapter(odin.ResourceAdapter):
  exclude = ['foo']

print(json_codec.dumps(MyResourceAdapter(MyResource(foo='1', bar='1'))))
```
prints the following JSON:
```json
{
  "foo": "1",
  "bar": "1",
  "$": "__main__.MyResource"
}
```

Passing exclude as a constructor argument works as expected as proven by the following code snippet:
```python
print(json_codec.dumps(MyResourceAdapter(MyResource(foo='1', bar='1'), exclude=['foo'])))
```

prints the following JSON:
```json
{
  "bar": "1",
  "$": "__main__.MyResource"
}
```

This could be a documentation issue but I'm not sure what is the right usage of the API to fix that.

**Comment by timsavage** [comment]
This is indeed an error in the documentation, excluded fields can be predefined using ResourceAdapter.curry to preset excluded fields.
The is quite a bit of filtering and pre-calculations done in the constructor.
Adaptors where a bit of a feature to scratch an itch at the time and are really designed as thin through away filters. I do have a replacement in mind in the form of ProxyResources that have a similar feature set but are a bit more flexable in their use and can be pre-defined, enhanced. I'm seeing the need for a better Proxy object with my work on odinweb.

**Comment by timsavage** [comment]
Work on ProxyResources is largely complete if you are interested in trying them out (feature/proxies branch). I am now in the process of extending the test suite to provide complete coverage of this new feature.

**Comment by timsavage** [comment]
The proxy feature will be in the next beta. Going to close this ticket.
