### ISSUE TITLE
Add a fallback to allow deserializing normal dictionaries as well

### ISSUE THREAD

**Issue by thedrow** [python-odin/odin#38]
I was hoping to use odin as my serializer for Celery but it is not possible since `build_object_graph` always raises an exception.
Instead it should have a keyword argument that will return the value it was provided with and the codecs should allow you to set it to True.

**Comment by timsavage** [comment]
Your use-case is not really what the codecs are designed for, there are explicitly for decoding resources, in this case I'd suggest a custom implementation of the loads method. eg:

    import json

    from odin.exceptions import ResourceException
    from odin.resources import create_resource_from_dict

    def loads_fallback(s, resource=None, full_clean=True, default_to_not_supplied):
        data = json.loads(s)
        try:
            return create_resource_from_dict(data, resource, full_clean, default_to_not_supplied
        except ResrouceException:
            return data

**Comment by thedrow** [comment]
What happens if I have multiple resources in a list? That bit of code won't do the trick.

**Comment by timsavage** [comment]
Swap in build_object_graph it is does a type check and calls the correct
built resource_from_TYPE command.
