### ISSUE TITLE
unexpected message when using simple_validators decorator

### ISSUE THREAD

**Issue by kristianmaras** [python-odin/odin#58]
import odin
    from odin.validators import simple_validator
    from odin.exceptions import ValidationError

    @simple_validator(message='age restrict')
    def age_validator(v):
        return bool(15.0 <= v <= 20.0)

    @simple_validator(message='age restrict')
    def age_validator_int(v):
        return bool(15 <= v <= 20)

    @simple_validator(message=' checking the name is in list')
    def name_validator(v):
        return v in ['bob','bill']

    class person(odin.Resource):
        name = odin.StringField()
        age = odin.FloatField(validators = [age_validator,])
        ageint = odin.FloatField(validators = [age_validator_int,])

    class person2(odin.Resource):
        name = odin.StringField(validators = [name_validator,])
        age = odin.FloatField()
        ageint = odin.FloatField()        

    def test():
        # Works as expected
        per2 = person2(name="bill",age=18.5,ageint=19)
        per2.full_clean()

        #Unexpected message rather the 'age restrict message' :
        # same functionality with simple_validator is inconsistent message with either int or float attribute 
        # "'{'show_value': 25.5}' value must be a float."
        per1 = person(name="bill",age=25.5,ageint=18)
        per1.full_clean()

    test()

**Comment by timsavage** [comment]
Looks like there is a bug. 

Is there a reason to not use the `min_value` and `max_value` arguments of the float field?
